name: object_path
description: Access and manipulate deep properties and any intermediaries using list notation ['a','b',c'] OR dot notation "a.b.c".
version: 0.0.1-dev.1
homepage: https://github.com/Ferdzzzzzzzz/object_path

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  pretty_json:
