name: object_path
description: Access and manipulate deep properties and any intermediaries using list notation ['a','b',c'] OR dot notation "a.b.c".
version: 0.0.1-dev.1
homepage: https://github.com/Ferdzzzzzzzz/object_path

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.12
  pretty_json: ^2.0.0
